// To parse this JSON data, do
//
//     final article = articleFromJson(jsonString);

import 'dart:convert';

Autogenerated articleFromJson(String str) =>
    Autogenerated.fromJson(json.decode(str));

String welcomeToJson(Autogenerated data) => json.encode(data.toJson());

class Autogenerated {
  Autogenerated({
    required this.count,
    required this.rows,
  });

  int count;
  List<Article> rows;

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
        count: json["count"],
        rows: List<Article>.from(json["rows"].map((x) => Article.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "count": count,
        "rows": List<dynamic>.from(rows.map((x) => x.toJson())),
      };
}

class Article {
  Article({
    required this.articleId,
    required this.title,
    required this.keyword,
    required this.category,
    required this.content,
    required this.image,
    required this.createdAt,
    required this.createdBy,
  });

  String articleId;
  String title;
  String keyword;
  String category;
  String content;
  String image;
  DateTime createdAt;
  String createdBy;

  factory Article.fromJson(Map<String, dynamic> json) => Article(
        articleId: json["article_id"],
        title: json["title"],
        keyword: json["keyword"],
        category: json["category"],
        content: json["content"],
        image: json["image"],
        createdAt: DateTime.parse(json["created_at"]),
        createdBy: json["created_by"],
      );

  Map<String, dynamic> toJson() => {
        "article_id": articleId,
        "title": title,
        "keyword": keyword,
        "category": category,
        "content": content,
        "image": image,
        "created_at":
            "${createdAt.year.toString().padLeft(4, '0')}-${createdAt.month.toString().padLeft(2, '0')}-${createdAt.day.toString().padLeft(2, '0')}",
        "created_by": createdBy,
      };
}
