// To parse this JSON data, do
//
//     final article = articleFromJson(jsonString);

import 'dart:convert';

Autogenerated articleFromJson(String str) =>
    Autogenerated.fromJson(json.decode(str));

String articleToJson(Autogenerated data) => json.encode(data.toJson());

class Autogenerated {
  Autogenerated(
      {required this.totalItems,
      required this.totalPages,
      required this.currentPage,
      required this.data});

  int totalItems;
  int totalPages;
  int currentPage;
  List<Article> data;

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
        totalItems: json["totalItems"],
        totalPages: json["totalPages"],
        currentPage: json["currentPage"],
        data: List<Article>.from(json["data"].map((x) => Article.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "totalItems": totalItems,
        "totalPages": totalPages,
        "currentPage": currentPage,
        "data": List<dynamic>.from(data.map((x) => x.toJson())),
      };
}

class Article {
  Article({
    required this.articleId,
    required this.title,
    required this.keyword,
    required this.category,
    required this.content,
    required this.image,
    required this.createdAt,
    required this.createdBy,
  });

  String articleId;
  String title;
  String keyword;
  String category;
  String content;
  String image;
  DateTime createdAt;
  String createdBy;

  factory Article.fromJson(Map<String, dynamic> json) => Article(
        articleId: json["article_id"],
        title: json["title"],
        keyword: json["keyword"],
        category: json["category"],
        content: json["content"],
        image: json["image"],
        createdAt: DateTime.parse(json["created_at"]),
        createdBy: json["created_by"],
      );

  Map<String, dynamic> toJson() => {
        "article_id": articleId,
        "title": title,
        "keyword": keyword,
        "category": category,
        "content": content,
        "image": image,
        "created_at":
            "${createdAt.year.toString().padLeft(4, '0')}-${createdAt.month.toString().padLeft(2, '0')}-${createdAt.day.toString().padLeft(2, '0')}",
        "created_by": createdBy,
      };
}
